name: flip
description: 'A flashcards app.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  phosphor_flutter: ^2.0.0
  http: ^1.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
          style: normal
